### ISSUE TITLE
Source for ECG Data

### ISSUE THREAD

**Issue by mcrone** [PIA-Group/BioSPPy#10]
Thanks for an awesome tool! Is there possibly a library of different ECG signals to test with this? I'm thinking of like arrhythmia etc. Is it possible to use something like physionet data for example?

**Comment by capcarr** [comment]
It certainly is possible to use the library with any signal database, as long as you can get the signals into a numpy array.
Regarding Physionet, take a look at the [WFDB Software](https://physionet.org/physiotools/wfdb.shtml), particularly the [rdsamp](https://physionet.org/physiotools/wag/rdsamp-1.htm) tool, which can convert Physionet records into csv files, which are easily read into numpy.
