### ISSUE TITLE
Basestring error?

### ISSUE THREAD

**Issue by andmib** [PIA-Group/BioSPPy#11]
I'm trying to run this in a virtual environment (with Anaconda) on Python 2.7.3 or 2.7.4. I get the error "name basestring" is not defined when I try to run biosppy.ecg.ecg(signal=mydata, sampling_rate=1000,show=True).

What version of Python is recommended for use with this?

**Comment by capcarr** [comment]
Hi, could you please provide the complete stack trace? With a quick search I was only able to find basestring errors related to Python 3.

**Comment by andmib** [comment]
I realize the environment I was running it in was not Python 2.7 like I presumed it was. Sorry!
