### ISSUE TITLE
BVP filter

### ISSUE THREAD

**Issue by ghost** [PIA-Group/BioSPPy#2]
I was wondering why you are filtering the BVP signal with a lowpass 4Hz butterworth filter? 
Is it meant to be a LP 40 Hz filter?

**Comment by capcarr** [comment]
Indeed, the parameters of the BVP filter are wrong. It should be a 1 Hz to 8 Hz bandpass filter. This is based on typical values found in the literature, as mentioned in this [paper](http://ieeexplore.ieee.org/xpl/login.jsp?tp=&arnumber=6127029).

I'll make the changes and release a new version.
