### ISSUE TITLE
Heart Rate Variability

### ISSUE THREAD

**Issue by DominiqueMakowski** [PIA-Group/BioSPPy#20]
I was just wondering, are there any plans for implementing HRV computation?

Thanks!

**Comment by capcarr** [comment]
Hi @DominiqueMakowski 
At the moment there isn't anything planned regarding HRV, but it certainly would be a nice addition to the toolbox. Do you have any specific requirements or features that you would like to see?

**Comment by DominiqueMakowski** [comment]
Dear @capcarr

From what I understood, the HRV can be computed with [different methods](https://en.wikipedia.org/wiki/Heart_rate_variability). One of them computes it accross the different frequencies. For example, the HRV in low frequency (0.06-0.10 Hz) is often used as an [accurate reflection of sympathetic activity](https://www.ncbi.nlm.nih.gov/pubmed/9887035), while the HRV in high frequency would correspond to the valgus nerve activity.

As such, it would be very nice to have a function that takes in the ECG and the RESP channels (as I believe that both a required for the computation) to return the HRV in these different frequency domains. That would be great both from a clinical and a research point of view.

Moreover, I've found only one [python package](https://github.com/rhenanbartels/hrv) devoted to HRV computation, but it lacks minimal examples and documentation, thus being non-usable.

Altough I know not much about signal processing or the statistics behind the hrv, let me know if you need any help for testing or anything else 😉

**Comment by DominiqueMakowski** [comment]
@capcarr 

I succeeded at working it out with the help of the creator of the [hrv](https://github.com/rhenanbartels/hrv) package. I created a convenient wrapper [function](https://github.com/neuropsychology/NeuroKit.py/blob/master/neurokit/bio/bio_ecg.py) to integrate your function and that of hrv. Of course, I credited your fantastic work as much as I could 😸 I hope it doesn't bother you.

Do not hesitate to give me some advices or make some modifications!

Thanks a lot,

**Comment by capcarr** [comment]
Awesome ;)
