### ISSUE TITLE
Find respiratory cycles

### ISSUE THREAD

**Issue by DominiqueMakowski** [PIA-Group/BioSPPy#21]
It's me again 😅 
I'm looking for a way to locate respiratory cycles. To get a list of indices corresponding to the beginning of each cycle. Currently, the `rsp.rsp()` function returns zero-crossings, which are not exactly the same... do you have any idea on how to achieve that?
again, thanks

**Comment by Maiisoenaingtun** [comment]
I’m has.

**Comment by DominiqueMakowski** [comment]
For the record, this has been implemented in the [NeuroKit2 package](https://github.com/neuropsychology/NeuroKit)
