### ISSUE TITLE
Implications of using Lead II ECG data?

### ISSUE THREAD

**Issue by stjep** [PIA-Group/BioSPPy#29]
I noticed that the ECG routine [assumes a single-channel Lead I](https://github.com/PIA-Group/BioSPPy/blob/master/biosppy/signals/ecg.py#L7) ECG signal.

Are there any implications for using the code on Lead II data?

**Comment by capcarr** [comment]
Hi @stjep 
The algorithms should work with lead II data, but they were only tested with lead I databases.
