### ISSUE TITLE
ICP

### ISSUE THREAD

**Issue by vkav** [PIA-Group/BioSPPy#31]
Hi!
I'm a medical researcher studying intracranial pressure (ICP) responses to various treatment interventions in intensive care unit patients. I was wondering if I can use BioSPPy to process and visualize ICP signals. I wouldn't assume it being more different than other signals like ecg-eeg etc. but it's not among the biosignals covered in the documentation.
Thanks in advance!

**Comment by capcarr** [comment]
Hi @vkav 
It's certainly possible to use the toolbox to process your signals, as there are various general purpose methods in the `biosppy.signals.tools` module. However, there is nothing planned in the roadmap to support ICP signals. If you implement something in that regard, please consider submitting a pull request ;)
