### ISSUE TITLE
Loading Acqknowledge files 

### ISSUE THREAD

**Issue by bobchicken** [PIA-Group/BioSPPy#32]
Hi this might be a stupid question - I don't have much experience working with Python/Signal processing...

I have acquired my data with Biopac Acqknowledge and converted the signals into a text file. When trying to load it with the np.loadtxt command I get errors 'ValueError: could not convert string to float:' . Does Biosppy not support the acqknowledge outputs? 

Thanks,

**Comment by stjep** [comment]
Open the file, if it contains anything other than numbers (for example the channel names), then that is causing your error.

Your best in working with AcqKnowledge files is to use [bioread](https://github.com/njvack/bioread) and deal with the data coming out of that. This means that you can keep the AcqKnowledge files in their native format (.acq).

**Comment by capcarr** [comment]
Hi @bobchicken 
BioSPPy does not directly support any kind of proprietary file format. But it works with any signal, as long as you are able to load it onto a numpy array.
I would follow @stjep's suggestion of using  [bioread](https://github.com/njvack/bioread).
