### ISSUE TITLE
ecg.ecg sometimes duplicates R peaks

### ISSUE THREAD

**Issue by stefperf** [PIA-Group/BioSPPy#35]
The function ecg.ecg sometimes reports the same R peak twice in a row, which may cause users' own downstream processing to fail (by calculating an R-R distance of zero). The corresponding heartbeat wave templates also get duplicated.
This happens, for example, at index 33 & 34 of the returned out['rpeaks'] and out['templates'] when the attached ecg is given as input.

[ecg_resulting_in_duplicated_rpeaks.npy.zip](https://github.com/PIA-Group/BioSPPy/files/1503343/ecg_resulting_in_duplicated_rpeaks.npy.zip)

**Comment by capcarr** [comment]
Hi @stefperf 
Could you please indicate the sampling frequency of the signal, and the version of `biosppy` that you have installed?

**Comment by stefperf** [comment]
Biosppy version = 0.5.0 
sampling frequency = 300 Hz
(sorry for not realizing myself that this data was also needed)
