### ISSUE TITLE
Paper reference of how the bvp algorithm was implemented

### ISSUE THREAD

**Issue by qiriro** [PIA-Group/BioSPPy#36]
I am trying to understand how [BVP peaks](https://github.com/PIA-Group/BioSPPy/blob/master/biosppy/signals/bvp.py) are detected. Is the  BVP onsets detection algorithm based on any published work? If there is, I would love to read it to make sense of how the algorithms were implemented.

**Comment by capcarr** [comment]
Hi @Qiriro 
The algorithm is based on this paper:
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.309.3442&rep=rep1&type=pdf

I'll update the docstrings.
