### ISSUE TITLE
Pan-Tompkins QRS Segmenter

### ISSUE THREAD

**Issue by parry-do** [PIA-Group/BioSPPy#37]
I'm doing HRV research. My team is most comfortable with the the Pan-Tompkins R peak detection algorithm since it is old and established. While Biosppy has many good segmenters, including the Hamilton segmenter used by default in biosppy.signals.ecg.ecg, it would be nice to have an old workhorse like Pan-Tompkins available in biosppy.

Would I be welcome to submit a fork adding Pan-Tompkins to biosppy?

**Comment by capcarr** [comment]
Hi @parry-do 
I'd be happy to review your code. Thanks for your help in making BioSPPy a better toolbox.
I'll close this issue now and wait for your pull request.
