### ISSUE TITLE
Walktree not working

### ISSUE THREAD

**Issue by mc-m** [PIA-Group/BioSPPy#38]
I can't seem to obtain any resut from the walktree function.

I'm doing this: filename = walktree(top= '../../data/Trials', spec=`r'\.XML$'`)

and the function acts like if I had no file in that directory whatsoever  (see images for better understanding).

Thank you

<img width="609" alt="cenas" src="https://user-images.githubusercontent.com/38071699/38305069-5ffcfb64-3803-11e8-850d-bfde813604f1.png">
<img width="258" alt="sem titulo" src="https://user-images.githubusercontent.com/38071699/38305070-6026181e-3803-11e8-9eb3-8ac9aaa56c1e.png">

**Comment by capcarr** [comment]
Hi @mc-m 
It seems that in your call to `walktree` you have two extra \`
It should just be `r'\.txt$'`

**Comment by mc-m** [comment]
Yes, you were right, thank you!

However, I'm getting another error. Not sure if it's about this fuction or not.

<img width="419" alt="github" src="https://user-images.githubusercontent.com/38071699/38490425-f79e3bd2-3be0-11e8-98ec-7146a3e30312.png">


Also, @capcarr, how does the function return the file names when there's more than one? Is it a list?

Thank you,

**Comment by capcarr** [comment]
Hi @mc-m 

The function returns a [generator function](https://www.programiz.com/python-programming/generator), which are useful in iterative loops.

You can obtain a list with all the elements by doing:
`files = list(walktree(...))`

Regarding your error, it seems that you are feeding the variable `filename` to another function, which expects a string. You probably wanted to pass `f`.
