### ISSUE TITLE
ImportError: cannot import name 'tools'

### ISSUE THREAD

**Issue by zneha** [PIA-Group/BioSPPy#41]
when i run the ecg.py code under BioSPPy-master/biosppy/signals i get this error, ImportError: cannot import name 'tools'

**Comment by capcarr** [comment]
Hi @zneha 
How did you install BioSPPy? How are you importing the module?

**Comment by zneha** [comment]
I cloned the project onto the system and when i run the code, it gives me
the import error.

**Comment by capcarr** [comment]
You are probably trying to import the module from within the package, which uses relative imports.
Try to call `python setup.py install` from the repo's root folder (where the `setup.py` file is) and then importing the module with `from biosppy.signals import ecg`.
