### ISSUE TITLE
AttributeError: module 'neurokit' has no attribute 'bio_process'

### ISSUE THREAD

**Issue by ghost** [PIA-Group/BioSPPy#42]
I just wanted to try the features of your neurokit.
I´m using Anaconda installed on Windows 10.
The pip install of neurokit was successful.
Then I copied your following sample code into a Spyder window:
 
# Import packages
import neurokit as nk
import pandas as pd
import numpy as np
import seaborn as sns
# Download data
df = pd.read_csv("https://raw.githubusercontent.com/neuropsychology/NeuroKit.py/master/examples/Bio/bio_100Hz.csv")
# Plot it
df.plot()
# Process the signals
bio = nk.bio_process(ecg=df["ECG"], rsp=df["RSP"], eda=df["EDA"], add=df["Photosensor"], sampling_rate=100)
# Plot the processed dataframe, normalizing all variables for viewing purpose
nk.z_score(bio["df"]).plot()
pd.DataFrame(bio["ECG"]["Cardiac_Cycles"]).plot(legend=False)
 
The first part imcuding the first plot runs well until nk.bio_process where I get this error message:
bio = nk.bio_process(ecg=df["ECG"], rsp=df["RSP"], eda=df["EDA"], add=df["Photosensor"], sampling_rate=100)
AttributeError: module 'neurokit' has no attribute 'bio_process'
 
What went wrong ?

**Comment by capcarr** [comment]
Hi @ursusaquarius 
This seems an issue unrelated to `BioSPPy`.
You should submit this issue in the `NeuroKit` repo:
https://github.com/neuropsychology/NeuroKit.py
