### ISSUE TITLE
Eda.eda falsely returns 0 onsets in some signals

### ISSUE THREAD

**Issue by BissonTom** [PIA-Group/BioSPPy#43]
I am facing the issue that the eda.eda method returns 0 onsets in some of my signals even though from visual inspection I can definitely see a lot of them. I already contacted Hugo Silva regarding this issue and he asked to raise my concern here on GitHub.

I already analyzed where the problem is and summarized my findings in the following pdf. I might be wrong so I would be glad to hear your opinion on this.
[Issues_with_SCR_library.pdf](https://github.com/PIA-Group/BioSPPy/files/2249035/Issues_with_SCR_library.pdf)

**Comment by capcarr** [comment]
Hi @Tomatenbiss 

Thanks for your analysis.
So do you think the best approach is to compute the threshold with the detrended derivative, or don't detrend at all? Could you test these modifications in your dataset?

**Comment by BissonTom** [comment]
Sorry for the late reply, I was off for vacation the last two weeks. I recommend not to detrend at all because the detrended derivative doesn't represent the exact gradient of the signal anymore.

**Comment by capcarr** [comment]
Ok, I'll make the change.
