### ISSUE TITLE
Amplitudes returned by EDA library are too small

### ISSUE THREAD

**Issue by BissonTom** [PIA-Group/BioSPPy#46]
I am facing the issue that the eda.eda method returns amplitudes that are significantly smaller than those in the EDA signal. I already analyzed where the problem is and summarized my findings in the following pdf. I might be wrong so I would be glad to hear your opinion on this.

[SCR_Library_Amplitudes.pdf](https://github.com/PIA-Group/BioSPPy/files/2410354/SCR_Library_Amplitudes.pdf)

**Comment by afonsocraposo** [comment]
Fixed with commit a324641b76ec6e5194c35b247a6d075fa6974940.
