### ISSUE TITLE
Possible error in timestamps

### ISSUE THREAD

**Issue by louisabraham** [PIA-Group/BioSPPy#48]
It seems to me endpoint should be True (the default).

https://github.com/PIA-Group/BioSPPy/blob/212c3dcbdb1ec43b70ba7199deb5eb22bcb78fd0/biosppy/signals/ecg.py#L102-L103

**Comment by capcarr** [comment]
You're right, thanks ;)
This also happens for the other signals (EDA, EMG, ...).

**Comment by flucchesi-Alpha** [comment]
Hi, has this been fixed? It looks like `endpoint=False` is still there.
Thanks.

**Comment by Marina168** [comment]
Hi! Could you tell my what are you using for measuring EDA signal and  which is the unit of measurement for  the values from BioSPPy/examples/eda.txt(microsiemeans, ohm ? ). Is that frequency real (1000 Hz)? Isn't it a too high  value?

**Comment by PatriciaBota** [comment]
> Hi! Could you tell my what are you using for measuring EDA signal and which is the unit of measurement for the values from BioSPPy/examples/eda.txt(microsiemeans, ohm ? ). Is that frequency real (1000 Hz)? Isn't it a too high value?

Hi, the unit is the ADC value with 12-bit (0-4095) resolution, you can find the transfer function here [EDA Sensor Datasheet.pdf](https://github.com/PIA-Group/BioSPPy/files/6063633/EDA.Sensor.Datasheet.pdf).

The choice of 1000Hz can be considered a high value for EDA when you have complexity and memory constrains, however a large sampling rate (SR) might be of interest when exploring spectral characteristics of EDA or decomposition algorithms. Additionally, when using a large SR, you can always downsample the data according to your work methods and goals. In contrast from using a small SR, which might introduce limitations.

**Comment by Marina168** [comment]
Thank you very much!
