### ISSUE TITLE
Segmentation Fault in IDLE or CLI

### ISSUE THREAD

**Issue by Xiaohong-Deng** [PIA-Group/BioSPPy#49]
The following scenarios are all in conda virtual environment

Simplest reproducible scenarios

Run the script in command line `python hello.py`

```python
import biosppy

if __name__ == '__main__':
    print("hello")
```
or in IDLE

```python
>>> import biosppy
```

In jupyter notebook it works fine. Any idea why it's the case?

**Comment by capcarr** [comment]
Hi @Xiaohong-Deng 

Can you show the exact error message that you get?
And the Python version you're using?
I'm assuming that in all cases you're pointing to the same conda environment, right?

**Comment by Xiaohong-Deng** [comment]
Resolved. It's long existing issue between Qt5 and matplotlib. Before `import biosppy` first

```python
    import matplotlib as mpl
    mpl.use('TkAgg')
    from matplotlib import pyplot as plt
```
I should have known it because I encountered this before.
