### ISSUE TITLE
Unable to get Rpeaks with ecg.engzee_segmenter

### ISSUE THREAD

**Issue by ymmx** [PIA-Group/BioSPPy#52]
I'm trying to get Rpeaks from ECG with all segmenters implemented in BioSPPY.signal.ecg.
All of them work except for the engzee_segmenter which gives no Rpeak at all.  The other ones give correct 30 RPeaks.

I try to change the threshold but no of my test was successful.

Does it exist a method to choose the threshold?

**Comment by capcarr** [comment]
Hi @ymmx 

There isn't a straightforward method to choose the threshold besides trial and error.
Please make sure the `sampling_rate` input argument is correct, as there are a lot internal algorithm parameters that depend on this.
Without having your ECG signal, it's hard for me to help further...
