### ISSUE TITLE
FutureWarning from scipy

### ISSUE THREAD

**Issue by lehippie** [PIA-Group/BioSPPy#59]
Hello,

Thank you for your work. I am currently working wth biosppy to process ECG signals. It's been of great help so far.

However, I have some warnings thrown at me using signals.ecg:

```lib/python3.6/site-packages/scipy/signal/_arraytools.py:45: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
b = a[a_slice]```

This same message appears for _arraytools.py (the example) and signaltools.py:1341, :1344 and :1350

The result from biosppy is correct but I wonder until when.

**Comment by lehippie** [comment]
Hello again,
I updated my scipy package to version 1.2 to get rid of the warnings.
So far, the results of biosppy.signals.ecg seems identical to previous results.

If the same is observed on other signals, requirements.txt should be updated.

**Comment by afonsocraposo** [comment]
Fixed with commit https://github.com/PIA-Group/BioSPPy/commit/4b222662542cbb7c0cde13b2a0bdcb0922f4e486.
