### ISSUE TITLE
Future Warning from sklearn

### ISSUE THREAD

**Issue by Xiaohong-Deng** [PIA-Group/BioSPPy#62]
The warning comes from `storage.py`. I think there is a two lines fix. I can create a pull request if it is appropriate. Thanks.

```
DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. 

Please import this functionality directly from joblib, which can be installed with: pip install joblib. 
If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.

  warnings.warn(msg, category=DeprecationWarning)
```

**Comment by finetard** [comment]
Created a pull request resolving this issue. Hoping that will be looked into and merged
#65

**Comment by ghosharindam** [comment]
Can someone review the relevant PR? sklearn is currently at a stable version of 0.23.2 and `sklearn.externals.joblib` leads to `ImportError: cannot import name 'joblib' from 'sklearn.externals'`

Only solution currently is downgrading sklearn.

@finetard would it be possible to assign the PR to someone else? @capcarr  seems to be presently inactive

**Comment by finetard** [comment]
@ghosharindam I don't know how to change the reviewer, do I have to issue another PR?

**Comment by finetard** [comment]
@DominiqueMakowski @herrkaefer  @ball-hayden can any of you look into it?

**Comment by ball-hayden** [comment]
I don't remember anything about this project. Sorry.

**Comment by finetard** [comment]
@LeafarCoder can you look into it?

**Comment by LeafarCoder** [comment]
I'm not free at the moment to solve this issue. If until the next month no one solves it I may be free by then to have a look.

**Comment by MadHuslista** [comment]
@LeafarCoder, Hi! Until today is still not solved, could yo look into it? 
Thanks in advance!

**Comment by MadHuslista** [comment]
> Created a pull request resolving this issue. Hoping that will be looked into and merged
> #65

Hi everyone, 
I believe that I solved the issue copying the changes recommended in #65  and #74 
I'm new with biosppy but the error message disappears, and the package appears to work properly.

**Comment by afonsocraposo** [comment]
Thank you @MadHuslista for your input.
You were right, PRs #65 and #74 indeed fix this issue.
The lastest commit https://github.com/PIA-Group/BioSPPy/commit/57fd8887546ecfbeac158399031a90152fa2e4af merges this PRs.
