### ISSUE TITLE
Simple store the processed data

### ISSUE THREAD

**Issue by portas525** [PIA-Group/BioSPPy#66]
Hello,
I´m pretty new on GitHub but I love it to try a lot...
So I also used to analyse me eda-data with biosppy. The plotting works perfect.
To get more insights into my data I want to store the processed data (means the "table") which is the basic for plotting.
But how can I do this?
I have tried a lot of things (and stupid things)... but none worked... 
Maybe there is some one how can help me with this problem.
Thank you!
regards
portas525

**Comment by saichand07** [comment]
Use Numpy or Pandas libraries to save the data in different formats and Matplotlib or Librosa libraries you can use it for visualization/plotting.

**Comment by afonsocraposo** [comment]
Closing this due to no further responses. Feel free to comment if something is unclear.
