### ISSUE TITLE
eda basic_scr mismatch in returned indices

### ISSUE THREAD

**Issue by malfarasplux** [PIA-Group/BioSPPy#68]
[test_biosppy_basic_scr.zip](https://github.com/PIA-Group/BioSPPy/files/4420274/test_biosppy_basic_scr.zip)

eda.basic_scr method

The basic_scr seems to be cutting wrongly the returned indices. After detecting null-derivative singular points, onset and peak indices to be returned are arranged to be returned in pairs.
 
However, the way peaks and onsets are discarded leads to (peak,onset,peak,onset) returns instead of (onset,peak,onset,peak) returns that would be more meaningful.

https://github.com/PIA-Group/BioSPPy/blob/master/biosppy/signals/eda.py

**Comment by afonsocraposo** [comment]
Fixed with commit https://github.com/PIA-Group/BioSPPy/commit/709c6a121cfc3ea2181eb29f7c89049552cb5802.
