### ISSUE TITLE
BVP vs PPG

### ISSUE THREAD

**Issue by katarzyna-jablonska** [PIA-Group/BioSPPy#72]
Hello,
I really appreciate the work you made to create biosppy library. It's very usefull and clearly written. 
Recently I saw that you made some changes in your  github repository and you also recommend to use PPG function insted of BVP. For a while  now I have been working with analysing this signals from smartwatches: Empatica E5 and Samsung Galaxy Watch 3. There is a little mess in the literature with the proper definition of this signals. Could you explain me what do you mean by PPG and by BVP signal? Is there any difference between them?

Best regards, 
Katarzyna Jabłońska

**Comment by hugoslv** [comment]
Dear Katarzyna,

We're very glad to hear that you find this resource to be of added value to your work. Regarding the change in designation from BVP to PPG, we modified it to make naming of this module more consistent with the remaining ones. In particular, all modules were named after the underlying process (e.g. Electromyography, Electrocardiography, etc.).

In the case of the modified module, the underlying process used to obtain the signal is Photoplethysmography (PPG), while the Blood Volume Pulse (BVP) usually describes the wave contained within the PPG signal resulting from the blood volume changes over time.

Hope this answers your questions. If you have any further comments or need additional information, we'll be more than happy to support. 

Best regards,
Hugo Silva
