### ISSUE TITLE
Minimum required r-peaks not mentioned in documentation

### ISSUE THREAD

**Issue by sgolestanian** [PIA-Group/BioSPPy#78]
I was working with `biosppy.signals.ecg.ecg` and faced this error that says there is a minimum for number of beats to calculate heart rate. Please mention the minimum required heart beat in your documentation.

BTW I'm not using heart rate and just want the rpeaks, which method is the equivalent to this method's rpeaks?

**Comment by hugoslv** [comment]
Hi,

Many thanks for your message. The individual detectors are available in the ecg.py module: 
https://github.com/PIA-Group/BioSPPy/blob/master/biosppy/signals/ecg.py#L515
https://github.com/PIA-Group/BioSPPy/blob/master/biosppy/signals/ecg.py#L681
https://github.com/PIA-Group/BioSPPy/blob/master/biosppy/signals/ecg.py#L896
https://github.com/PIA-Group/BioSPPy/blob/master/biosppy/signals/ecg.py#L1206

For what you are seeking maybe it is the best option. If you have further questions, let us know.

Best regards,
Hugo Silva

**Comment by afonsocraposo** [comment]
Closing this due to no further responses. Feel free to comment if something is unclear.
