### ISSUE TITLE
Unable to import the bcg module in the latest version 

### ISSUE THREAD

**Issue by megrao** [PIA-Group/BioSPPy#81]
Here is the error -

ImportError                               Traceback (most recent call last)
<ipython-input-27-ac1deeb9c13f> in <module>
      1 from biosppy import storage
----> 2 from biosppy.signals import bcg
      3 
      4 # process it and plot
      5 out = bcg.bcg(signal=b1_s1_normbreath, sampling_rate=250, show=True)

ImportError: cannot import name 'bcg' from 'biosppy.signals' (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/biosppy/signals/__init__.py)

**Comment by megrao** [comment]
Hi, looks like __init__.py  does not include bcg in the import statement

**Comment by afonsocraposo** [comment]
Hi @megrao ,
You're right. Thank you for bringing up this issue!
Fixed in commit 89023f85c8b7f7ae0c21476c39674842c0c35974.

**Comment by megrao** [comment]
Hi @Afonsocraposo,
Thanks very much! In PyPi latest release, it would be great to have BCG as there are very few python packages that seem to process them.

**Comment by afonsocraposo** [comment]
Done :)
https://pypi.org/project/biosppy/

**Comment by megrao** [comment]
Huge thanks! It will be immensely useful. I tried to do a test run and got the below error.


AttributeError                            Traceback (most recent call last)
<ipython-input-11-16b62863cce8> in <module>
      4 
      5 # process it and plot
----> 6 out = bcg.bcg(signal=norm_breath, sampling_rate=250, show=True)

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/biosppy/signals/bcg.py in bcg(signal, sampling_rate, show)
    102     # plot
    103     if show:
--> 104         plotting.plot_bcg(ts=ts,
    105                           raw=signal,
    106                           filtered=filtered,

**AttributeError: module 'biosppy.plotting' has no attribute 'plot_bcg'**

**Comment by afonsocraposo** [comment]
I updated the version on PyPI to 0.7.2. Maybe wait a bit so PyPI update the available version. You can always clone the repository and use it on your project doing:
```python
import sys
sys.path.insert(0, '/path/to/BioSPPy')
import biosppy
```

**Comment by megrao** [comment]
Great, thanks very much! I just wanted to let you know of any errors I encounter. It works perfectly now.
