### ISSUE TITLE
ValueError: too many values to unpack (expected 1)

### ISSUE THREAD

**Issue by FilippoL** [PIA-Group/BioSPPy#83]
In signals/bvp.py at line 76, you are missing another variable containing the unpacked result of the find_onsets_elgendi2013 function. 

To replicate the ValueError just call the bvp.bvp() function on some pulse data. 

In my example:

`biosppy.bvp.bvp(pulse, 256)`

**Comment by afonsocraposo** [comment]
Thank you for bringing this up. I'll fix it as soon as possible!
