### ISSUE TITLE
How to use biosppy.clustering 

### ISSUE THREAD

**Issue by alexxony** [PIA-Group/BioSPPy#85]
I saw API reference, but I can not apply clustering on my data(1 dimension). 
Can you upload examples for understanding clustering?

**Comment by afonsocraposo** [comment]
Hi, you can test the k-means algorithm, for example.
You could use the following code:
```python
kmeans(np.array(data).reshape(-1,1), 3)
```
And the output will be:
*"Dictionary with the sample indices (rows from 'data') for each found cluster; outliers have key -1; clusters are assigned integer keys starting at 0."*
