### ISSUE TITLE
ACC not found

### ISSUE THREAD

**Issue by karoanja** [PIA-Group/BioSPPy#87]
Hi, 
Acc.py can't be found in python after importing biosppy.
Could you please fix that problem ? You might need to add it in the __init__ ?
Thank you.

**Comment by afonsocraposo** [comment]
Thank you for raising this issue. I added `acc.py` to the `__init__.py` and your issue should be fixed now.

**Comment by karoanja** [comment]
Thank you. Could you please also add it to biosppy.signals.__init__?

**Comment by afonsocraposo** [comment]
Done :)
Thank you for pointing that out!
